Repository avast/slog4s, pull requests merged in 2020-02, with the labels that each got.

#39 feat(console): add json format
  build.sbt
  console/src/main/scala/slog4s/console/ConsoleFactory.scala
  console/src/main/scala/slog4s/console/ConsoleLoggingContext.scala
  console/src/main/scala/slog4s/console/Format.scala
  console/src/main/scala/slog4s/console/internal/JsonFormatter.scala
  console/src/main/scala/slog4s/console/package.scala
  console/src/test/scala/slog4s/console/ConsoleLoggerTest.scala
  console/src/test/scala/slog4s/console/JsonTest.scala
  console/src/test/scala/slog4s/console/PlainTest.scala
  example/src/main/scala/example/Example.scala
  project/Dependencies.scala
Labels: feature

#40 Update sbt to 1.3.8
  project/build.properties
Labels: chore

#41 Update diffx-scalatest to 0.3.17
  project/Dependencies.scala
Labels: chore

#45 Update sbt-ci-release to 1.5.2
  project/plugins.sbt
Labels: chore

#44 Update cats-effect to 2.1.1
  project/Dependencies.scala
Labels: chore

#43 Update sourcecode to 0.2.1
  project/Dependencies.scala
Labels: chore

#42 fix: Wrong indentation of microsite menu config
  site/menu.yml
Labels: docs

#46 Update scala-collection-compat to 2.1.4
  project/Dependencies.scala
Labels: chore

#48 feat(console): add support for structured configuration
  api/src/test/scala/slog4s/EffectTest.scala
  build.sbt
  console/src/main/scala/slog4s/console/ConsoleConfig.scala
  console/src/main/scala/slog4s/console/internal/StructuredConsoleConfig.scala
  console/src/main/scala/slog4s/console/package.scala
  console/src/test/scala/slog4s/console/ConsoleConfigTest.scala
  console/src/test/scala/slog4s/console/PlainTest.scala
Labels: feature

#50 docs: improved scaladoc
  console/src/main/scala/slog4s/console/ConsoleConfig.scala
  console/src/main/scala/slog4s/console/ConsoleFactory.scala
  console/src/main/scala/slog4s/console/ConsoleLoggingContext.scala
  console/src/main/scala/slog4s/console/Format.scala
  console/src/main/scala/slog4s/console/Level.scala
  shared/src/main/scala/slog4s/shared/ContextRuntime.scala
  shared/src/main/scala/slog4s/shared/ContextRuntimeBuilder.scala
  shared/src/main/scala/slog4s/shared/LoggingRuntime.scala
  site/docs/overview.md
Labels: docs

#51 Access
  console/src/main/scala/slog4s/console/ConsoleFactory.scala
Labels: chore

#49 Update circe-core, circe-literal, ... to 0.13.0
  project/Dependencies.scala
Labels: chore

#55 build: run unidoc on check
  build.sbt
Labels: build

#53 Update scalatest to 3.1.1
  project/Dependencies.scala
Labels: chore

#54 Update sbt-microsites to 1.1.2
  project/plugins.sbt
Labels: chore

#56 ci: trigger release on published release
  .github/workflows/release.yml
Labels: ci

#57 chore: update scalafmt to 2.4.1
  .scalafmt.conf
  api/src/main/scala/slog4s/WhenEnabledLogBuilder.scala
  console/src/main/scala/slog4s/console/internal/PlainFormatter.scala
  monix/src/main/scala/slog4s/monix/UseMonixContext.scala
  project/Dependencies.scala
  slf4j/src/test/scala/slog4s/slf4j/Slf4jLoggerTest.scala
Labels: chore

#61 Update cats-core to 2.1.1
  project/Dependencies.scala
Labels: chore

#60 Update magnolia to 0.12.7
  project/Dependencies.scala
Labels: chore

#59 Update diffx-scalatest to 0.3.18
  project/Dependencies.scala
Labels: chore

#58 Update scalafmt-core to 2.4.2
  .scalafmt.conf
Labels: chore
