Repository avast/slog4s, pull requests merged in 2020-03, with the labels that each got.

#62 Update cats-effect to 2.1.2
  project/Dependencies.scala
Labels: chore

#63 feat: improved and unified factory API
  console/src/main/scala/slog4s/console/ConsoleFactory.scala
  console/src/main/scala/slog4s/console/internal/LoggingRuntimeImpl.scala
  console/src/test/scala/slog4s/console/ConsoleLoggerTest.scala
  example/src/main/scala/example/Example.scala
  shared/src/main/scala/slog4s/shared/ContextRuntime.scala
  shared/src/main/scala/slog4s/shared/ContextRuntimeBuilder.scala
  site/docs/integrations/monix.md
  site/docs/integrations/zio.md
  slf4j/src/main/scala/slog4s/slf4j/Slf4jFactory.scala
Labels: feature

#64 Update magnolia to 0.12.8
  project/Dependencies.scala
Labels: chore

#66 Update cats-mtl-core to 0.7.1
  project/Dependencies.scala
Labels: chore

#71 fix: Add all modules to root project aggregate
  build.sbt
Labels: bug

#75 feat: Add LoggerFactory.noop
  api/src/main/scala/slog4s/LoggerFactory.scala
Labels: feature

#70 Update sbt-microsites to 1.1.5
  project/plugins.sbt
Labels: chore

#68 Update diffx-scalatest to 0.3.19
  project/Dependencies.scala
Labels: chore

#76 feat(generic): Nicer LogEncoder for case object
  generic/src/main/scala/slog4s/generic/internal/Common.scala
  generic/src/test/scala/slog4s/generic/DerivationTest.scala
Labels: feature

#77 fix: properly test sealed trait derivation
  generic/src/test/scala/slog4s/generic/DerivationTest.scala
Labels: bug

#78 Update diffx-scalatest to 0.3.20
  project/Dependencies.scala
Labels: chore
